{
 "title": "XLayer",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.0,0.25,0.5, 0.9, 0.97, 0.99, 1"
   },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Sequencer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transaction Per Second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "rate(sequencer_tx_count{instance=\"xlayer-seq:9095\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Gas Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sequencer_block_gas_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sequencer_pool_tx_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_tx_count{instance=\"xlayer-seq:9095\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_fail_tx_count{instance=\"xlayer-seq:9095\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
     "legendFormat": "success {{ method }} {{ instance }} "
    },
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
     "legendFormat": "failure {{ method }} {{ instance }} "
    }
   ]
  },
  {
   "title": "RPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rpc_duration_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": " {{ method }} {{ instance }} {{ success }}"
    }
   ]
  },
  {
   "title": "Dynamic Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "GWei" } },
   "targets": [
    {
     "expr": "rpc_dynamic_gas_price{instance=\"xlayer-seq:9095\"}/1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inner Transaction Executed",
   "type": "timeseries",
   "description": "Trace contract calls on OKLink\nExample: \nhttps://www.oklink.com/zh-hans/xlayer/tx/0x60d98f5b2ef33de2d1697bd57ee4b3f1ff0ce86aca2adc528ca647add430f173/internal",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    { "expr": "rpc_inner_tx_executed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\",stage=\"headers\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_basefee{instance=~\"$instance\"}",
     "legendFormat": "basefee: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "current: {{ instance }}"
    }
   ]
  },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\"}",
     "legendFormat": "{{ stage }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    },
    {
     "expr": "db_mi_last_pgno{instance=~\"$instance\"}",
     "legendFormat": "db_mi_last_pgno: {{instance}}"
    }
   ]
  }
 ]
}